fix yaml errors

diff --git a/.github/workflows/verify_failure.yml b/.github/workflows/verify_failure.yml
--- a/.github/workflows/verify_failure.yml
+++ b/.github/workflows/verify_failure.yml
@@ -2,29 +2,27 @@ name: Verify Assertion Failure
 
 on:
   push:
-    branches: 
+    branches:
     branches: [master]
   pull_request:
     branches: [master]
 
 jobs:
   test-native:
-    build:
-      runs-on: macos-latest
-
-      steps:
+    runs-on: ubuntu-latest
+    steps:
         - name: Checkout repository
           uses: actions/checkout@v4
 
         - name: Build
           run: |
-              cd test     
+              cd test
               cmake -B build
               cmake --build build -j 8
 
         - name: Verify assertion fails
           run: |
-            cd test 
+            cd test
             if ./build/Example; then
               echo "ERROR: Test should have failed but passed"
               exit 1
@@ -37,21 +35,22 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      
+
       - uses: mymindstorm/setup-emsdk@v14
 
-      - name: Build emscripten test
+      - name: Build
         run: |
           cd test
-          emcmake cmake -B web-build
-          cmake --build web-build
-      
-        - name: Verify assertion fails
-          run: |
-            if node web-build/Example.js; then
-              echo "ERROR: Test should have failed"
-              exit 1
-            else
-              echo "Test failed as expected"
-              exit 0
-            fi
+          emcmake -B web-build
+          cmake --build web-build -j 8
+
+      - name: Verify assertion fails
+        run: |
+          cd test
+          if node web-build/Example.js; then
+            echo "ERROR: Test should have failed"
+            exit 1
+          else
+            echo "Test failed as expected"
+            exit 0
+          fi
